-- MySQL Script generated by MySQL Workbench
-- Sat 22 May 2016 21:15:48 AM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `chat` ;

-- -----------------------------------------------------
-- Table `chat`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `date` DATE NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chat`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
PACK_KEYS = DEFAULT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `chat`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `chat`;
INSERT INTO `chat`.`Users` (`name`) VALUE ('Vasia');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Lena');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Kate');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Alex');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Angela');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Bob');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Tim');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Jack');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Simion');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Liza');

COMMIT;


-- -----------------------------------------------------
-- Data for table `chat`.`Messages`
-- -----------------------------------------------------
START TRANSACTION;
USE `chat`;
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Hi', '2015-02-27', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Hello', '2015-02-27', 2);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ('How are you?', '2015-02-28', 2);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'I\'m fine', '2015-02-28', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Bla-la-la', '2015-02-28', 3);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'It is time to cry', '2015-05-09', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Hey guys', '2015-05-09', 2);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Wazzup', '2015-05-09', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ('I wanna do it again', '2015-05-09', 3);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ('First night staying up all night', '2015-05-10', 2);

COMMIT;

